[pytest]
testpaths = postman_api_sample_tests
addopts = -m "postman" -s -v --html=report.html
markers =
    postman: all cases using postman open API endpoints
    parametrized: cases with parametrization
